language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - cmake --build .
  - ctest -V .

after_script:
  - export SITE_NAME="Travis (${CXX})"
  - echo ${SITE_NAME}
  - ctest -D Experimental
