language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - ctest -VV -S ../CMake/travis_build.cmake

after_script:
  - ctest -VV -S ../CMake/travis_submit.cmake
